spring:
  application:
    name: pjt-redis
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Seoul
  serialization:
    write-dates-as-timestamps: false
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379

