spring:
  application:
    name: pjt-redis
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Seoul
  serialization:
    write-dates-as-timestamps: false
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:mysql://localhost:3306/local?autoReconnect=true
    username: root
    password: root
    hikari:
      maximum-pool-size: 5
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    out-of-order: true
    baseline-on-migrate: true
    locations:
      - "classpath:db/migration"
