spring:
  application:
    name: pjt-redis
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Seoul
  serialization:
    write-dates-as-timestamps: false
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:ad-db
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 5
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    out-of-order: true
    baseline-on-migrate: true
    locations:
      - "classpath:db/migration"
