version: '3.8'
services:
  rdb:
    container_name: pjt-redis-mysql
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
      - ./db/conf.d:/etc/mysql/conf.d
    env_file: db/initdb.d/.env
    environment:
      TZ: Asia/Seoul
    networks:
      - redis-net

  redis:
    container_name: pjt-redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - redis-net

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    ports:
      - "8001:8001"  # 웹 UI 접근 포트
    networks:
      - redis-net
    restart: unless-stopped

networks:
  redis-net:
    driver: bridge
